// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJ0uc_V5qfNHpQtUu5aqWFvLTRlICUhw',
    appId: '1:834291206011:web:458a386fd6974ff5c1dfde',
    messagingSenderId: '834291206011',
    projectId: 'phoneauth-aaece',
    authDomain: 'phoneauth-aaece.firebaseapp.com',
    storageBucket: 'phoneauth-aaece.appspot.com',
    measurementId: 'G-GVDSFPN3QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYtjXCkx8Z6uXVUt87YWAnFZp0qgfgW8',
    appId: '1:834291206011:android:1e86c54bbc13a70ac1dfde',
    messagingSenderId: '834291206011',
    projectId: 'phoneauth-aaece',
    storageBucket: 'phoneauth-aaece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnelSfywu6YnjdeMKvrhPUf44u2I1kZo',
    appId: '1:834291206011:ios:5305345ead48ad2ec1dfde',
    messagingSenderId: '834291206011',
    projectId: 'phoneauth-aaece',
    storageBucket: 'phoneauth-aaece.appspot.com',
    iosBundleId: 'com.example.phoneNumber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnelSfywu6YnjdeMKvrhPUf44u2I1kZo',
    appId: '1:834291206011:ios:b61cb9d452a11eb6c1dfde',
    messagingSenderId: '834291206011',
    projectId: 'phoneauth-aaece',
    storageBucket: 'phoneauth-aaece.appspot.com',
    iosBundleId: 'com.example.phoneNumber.RunnerTests',
  );
}
